esphome:
  name: klimaanlage
  friendly_name: Klimaanlage

esp32:
  board: esp32dev


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "glXNdaZaLVlV8p2M0sYLNr+8BPt4zOU8HAhanEuRDCU="


substitutions:
  device_name: tclac
  humanly_name: TCL Air Conditioner
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  recovery_pass: mKSzmBdt7DAj
  ota_pass: 90cf525a594c8bb2cbf917bc2c2fa058
  uart_rx: GPIO1
  uart_tx: GPIO3
  receive_led: GPIO2
  transmit_led: GPIO2
  dht_pin: GPIO35

packages:
  remote_package:
    url: https://github.com/Kannnix2005/tclac.git     
    ref: master
    files:
      - packages/core.yaml
    refresh: 30s
    
