substitutions:
# Eindeutiger Name für diese Konfiguration – verwende nur lateinische Buchstaben und Zahlen,
# keine Leerzeichen oder Sonderzeichen, z. B. "tclac".
# Wenn du mehrere Klimamodule hast, muss device_name entsprechend geändert werden,
# z. B. durch Anhängen von Zahlen: tclac1, tclac2, tclac3…
  device_name: tclac
# Menschlich lesbarer Name für das Klimagerät, angezeigt in der Benutzeroberfläche:
  humanly_name: TCL Air Conditioner
# WLAN-Zugangsdaten – können alternativ in der Datei "secret" in ESPHome gespeichert sein, sonst hier bearbeiten:
# Name des WLAN-Netzwerks:
  wifi_ssid: !secret wifi_ssid
# WLAN-Passwort:
  wifi_password: !secret wifi_password
# Passwort für den Wiederherstellungsmodus – der Hotspot heißt dann: "{device_name} Fallback Hotspot"
  recovery_pass: mKSzmBdt7DAj
# Passwort für OTA-Updates – wird einmal generiert und dauerhaft verwendet:
  ota_pass: 90cf525a594c8bb2cbf917bc2c2fa058
# API-Schlüssel zur Verbindung mit Home Assistant – neuen Schlüssel hier generieren: https://esphome.io/components/api.html
  api_key: lmUoWsWs1oqSfJqLFsA6PisHSx4Y1G+iu7V3PDIqpXk=
# GPIO-Pins des Moduls, an die UART angeschlossen ist:
  uart_rx: GPIO3
  uart_tx: GPIO1
# GPIO-Pins für Status-LEDs (Empfang/Senden). Funktionieren nur, wenn "leds" in "packages" aktiviert ist.
# Falls du keine LEDs verwenden möchtest, kannst du hier beliebige Werte eintragen.
  receive_led: GPIO6
  transmit_led: GPIO4
# DHT Temperatursensor config
  dht_pin: GPIO35

# Eingebundene Dateien – werden automatisch aus dem Internet geladen und aktualisiert.
# Kommentiere die gewünschten Optionen ein.
# Beschreibung der Optionen:
# - packages/leds.yaml – LEDs zur Anzeige von Senden/Empfangen; Pins über receive_led / transmit_led definieren
#
# Alle eingetragenen Zeilen müssen exakt auf dieser Einrückungsebene stehen – sonst kommt es zu Fehlern!
packages:
  remote_package:
    url: https://github.com/Kannnix2005/tclac.git
    ref: master
    files:
    # v – Zeilen müssen exakt hier ausgerichtet sein, sonst gibt’s Probleme!
      - packages/core.yaml # Das Herzstück des Ganzen
      # - packages/leds.yaml
    refresh: 30s

# Ausgewähltes Modul, das mit dieser Firmware geflasht wird.
# Vorbereitete Konfigurationen können durch Entfernen des Kommentars verwendet werden:

# ESP-01S
esp8266:
  board: esp01_1m

# Hommyn HDN/WFN-02-01 (aus dem ersten Artikel)
#esp32:
#  board: esp32-c3-devkitm-1
#  framework:
#    type: arduino

# Status-LED – optional aktivieren, wenn freie Pins vorhanden sind
#status_led:
#  pin:
#    number: GPIO5
#    inverted: false
